server:
  port: 8181
spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:test_db;DATABASE_TO_UPPER=false;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;
    schema: classpath:schema.sql
    data: classpath:data.sql
  devtools:
    restart:
      enabled: true