server:
  port: 8181
spring:
  jpa:
    hibernate: ddl-auto:none
  datasource:
    platform: h2
    url: jdbc:h2:mem:test_db;DATABASE_TO_UPPER=false;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;
  devtools:
    restart:
      enabled: true